/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import Sound.Sound;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author Liam
 */
public class MainMenu extends javax.swing.JFrame {

public int status = 0; 

    /**
     * Creates new form MainMenu
     */
    
    
    public MainMenu() {
        
        initComponents();
      
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PestQuest = new javax.swing.JLabel();
        Play = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Controls = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(207, 446));
        setPreferredSize(new java.awt.Dimension(833, 638));
        getContentPane().setLayout(null);

        PestQuest.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liam\\Documents\\KiwiIsland Tests\\KiwiIsland\\KiwiIsland\\res\\textures\\Pest Quest.png")); // NOI18N
        getContentPane().add(PestQuest);
        PestQuest.setBounds(190, 30, 430, 140);

        Play.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        getContentPane().add(Play);
        Play.setBounds(300, 240, 180, 40);

        Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(300, 360, 180, 40);

        Controls.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Controls.setText("Controls");
        Controls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlsActionPerformed(evt);
            }
        });
        getContentPane().add(Controls);
        Controls.setBounds(300, 300, 180, 40);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liam\\Documents\\KiwiIsland Tests\\KiwiIsland\\KiwiIsland\\res\\textures\\Game background.png")); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Background.setMinimumSize(new java.awt.Dimension(207, 446));
        Background.setPreferredSize(new java.awt.Dimension(833, 638));
        getContentPane().add(Background);
        Background.setBounds(10, -60, 800, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
              
        // create the game object
        final Game game = new Game();
        // create the GUI for the game
        final KiwiCountUI  gui  = new KiwiCountUI(game);
        // make the GUI visible
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() 
            {
                gui.setVisible(true);
                //Enable Sound
                
                
            }
        });
        
        //Hides the Main Menu
        this.setVisible(false);
    }//GEN-LAST:event_PlayActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        // Quits the game
         System.exit(0) ;
    }//GEN-LAST:event_ExitActionPerformed

    private void ControlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlsActionPerformed
        // TODO add your handling code here:
        new Controls().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ControlsActionPerformed

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Controls;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel PestQuest;
    private javax.swing.JButton Play;
    // End of variables declaration//GEN-END:variables
}
