package nz.ac.aut.ense701.gui;


import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.GameEventListener;


/*
 * User interface form for Kiwi Island.
 * 
 * @author AS
 * @version July 2011
 */

public class Map 
    extends javax.swing.JFrame 
    implements GameEventListener
{

    /**
     * Creates a GUI for the KiwiIsland game.
     * @param game the game object to represent with this GUI.
     */
    public Map(Game game) 
    {
        assert game != null : "Make sure game object is created before UI";
        this.game = game;
        setAsGameListener();
        initComponents();
        update();
        
    }
    
    /**
     * This method is called by the game model every time something changes.
     */
    @Override
    public void gameStateChanged()
    {
        update();   
    }
    private void setAsGameListener()
    {
       game.addGameEventListener(this); 
    }
     
    /**
     * Updates the state of the UI based on the state of the game.
     */
    private void update()
    {
        
        // update player information
        int[] playerValues = game.getPlayerValues();
     
        //Update Kiwi and Predator information     
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Map = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mapBackgnd = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pest Quest");
        setMinimumSize(new java.awt.Dimension(207, 492));
        setPreferredSize(new java.awt.Dimension(815, 638));
        getContentPane().setLayout(null);

        Map.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liam Maddren\\Documents\\kiwiIslandTest\\FINAL\\KiwiIsland\\KiwiIsland\\res\\textures\\tMap.png")); // NOI18N
        Map.add(jLabel1);
        jLabel1.setBounds(590, 140, 160, 110);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Map.add(jButton1);
        jButton1.setBounds(630, 420, 80, 50);

        mapBackgnd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liam Maddren\\Documents\\kiwiIslandTest\\FINAL\\KiwiIsland\\KiwiIsland\\res\\textures\\fMap.png")); // NOI18N
        mapBackgnd.setPreferredSize(new java.awt.Dimension(836, 638));
        Map.add(mapBackgnd);
        mapBackgnd.setBounds(0, -30, 800, 660);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liam Maddren\\Documents\\kiwiIslandTest\\FINAL\\KiwiIsland\\KiwiIsland\\res\\textures\\Game background.png")); // NOI18N
        Background.setText("jLabel2");
        Map.add(Background);
        Background.setBounds(40, 0, 760, 610);

        getContentPane().add(Map);
        Map.setBounds(0, 0, 800, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final KiwiCountUI  gui  = new KiwiCountUI(game);
                
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() 
            {
                gui.setVisible(true);
                gui.setLocationRelativeTo(null);
            }
        });
        this.setVisible(false);
    
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Map;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mapBackgnd;
    // End of variables declaration//GEN-END:variables

    private Game game;
}
